export const GET_STRAVA_DATA = 'GET_STRAVA_DATA';
export const CLEAR_STRAVA_DATA = 'CLEAR_STRAVA_DATA';

export const SET_LOADING = 'SET_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const GET_RUNKEEPER_DATA = 'GET_RUNKEEPER_DATA';
export const CLEAR_RUNKEEPER_DATA = 'CLEAR_RUNKEEPER_DATA';
