export const SET_LOADING = 'SET_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const SET_RUNKEEPER_DATA = 'SET_RUNKEEPER_DATA';
export const CLEAR_RUNKEEPER_DATA = 'CLEAR_RUNKEEPER_DATA';
export const SET_WITHINGS_DATA = 'SET_WITHINGS_DATA';
export const CLEAR_WITHINGS_DATA = 'CLEAR_WITHINGS_DATA';
export const SET_MAPMYFITNESS_DATA = 'SET_MAPMYFITNESS_DATA';
export const CLEAR_MAPMYFITNESS_DATA = 'CLEAR_MAPMYFITNESS_DATA';
